FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

WORKDIR /mortal

RUN apt-get update && apt-get install -y \
    git curl build-essential python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install torch==2.1.2 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install tqdm toml tensorboard

RUN cargo build -p libriichi --lib --release
RUN cp target/release/libriichi.so mortal/libriichi.so

WORKDIR /mortal/mortal

CMD ["python3", "train_grp.py"]
